FROM node:12

EXPOSE 3001 8082
COPY ["./package.json", "./package-lock.json", "/app/"]
COPY ["./node-mongo", "/app/node-mongo/"]
WORKDIR /app
RUN npm ci --quiet

VOLUME "/app/src"

CMD npm run development
